#!/usr/bin/perl

# Utility to read two files, pad them both to a multiple of 4 bytes
# and write to stdout. The files are assumed to be less than 64KB.

use strict;
use warnings;
my $fh;

binmode(STDOUT);
while (defined $ARGV[0])
{
    my $arg = shift @ARGV;
    open $fh, "<", $arg or die "Could not open", $arg;
    binmode($fh);
    my $len = sysread $fh, my ($buf), 65536;
    my $pad = (($len & 3) != 0) ? 4 - ($len & 3) : 0;
    close $fh;
    
    print $buf, chr(0) x $pad
}
